### ISSUE TITLE
npm start fails: npm ERR! code ELIFECYCLE errno 1

### ISSUE THREAD

**Issue by DylanAllen** [tulsajs/tulsajs.com#2]
After the last meetup, I decided to jump into the code and fix some of the accessibility issues pointed out. However, I can't get the project to run. I tried deleting the node modules, clearing the NPM cache, and re-installing, but no dice.

debug log:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/dylanallen/.nvm/versions/node/v8.11.4/bin/node',
1 verbose cli   '/Users/dylanallen/.nvm/versions/node/v8.11.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle boilerplate-es6-angular-webpack@1.0.0~preserver: boilerplate-es6-angular-webpack@1.0.0
6 info lifecycle boilerplate-es6-angular-webpack@1.0.0~server: boilerplate-es6-angular-webpack@1.0.0
7 verbose lifecycle boilerplate-es6-angular-webpack@1.0.0~server: unsafe-perm in lifecycle true
8 verbose lifecycle boilerplate-es6-angular-webpack@1.0.0~server: PATH: /Users/dylanallen/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dylanallen/tulsajs/node_modules/.bin:/Users/dylanallen/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dylanallen/tulsajs/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/dylanallen/.nvm/versions/node/v8.11.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle boilerplate-es6-angular-webpack@1.0.0~server: CWD: /Users/dylanallen/tulsajs
10 silly lifecycle boilerplate-es6-angular-webpack@1.0.0~server: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --history-api-fallback --inline --progress' ]
11 silly lifecycle boilerplate-es6-angular-webpack@1.0.0~server: Returned: code: 1  signal: null
12 info lifecycle boilerplate-es6-angular-webpack@1.0.0~server: Failed to exec server script
13 verbose stack Error: boilerplate-es6-angular-webpack@1.0.0 server: `webpack-dev-server --history-api-fallback --inline --progress`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dylanallen/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dylanallen/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid boilerplate-es6-angular-webpack@1.0.0
15 verbose cwd /Users/dylanallen/tulsajs
16 verbose Darwin 18.2.0
17 verbose argv "/Users/dylanallen/.nvm/versions/node/v8.11.4/bin/node" "/Users/dylanallen/.nvm/versions/node/v8.11.4/bin/npm" "run" "server"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error boilerplate-es6-angular-webpack@1.0.0 server: `webpack-dev-server --history-api-fallback --inline --progress`
22 error Exit status 1
23 error Failed at the boilerplate-es6-angular-webpack@1.0.0 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nearbycoder** [comment]
I so totally missed this sorry @DylanAllen. I have just pushed a new codebase with React feel free to check it out and clean up any accessibility issues you find with this new site. Again sorry I must have notification turned off for this repo.
